config:
  target: 'http://localhost:8081'
  phases:
    - duration: 30
      arrivalRate: 3
      name: Warm up

  payload:
    path: "id-password.csv"
    fields:
      - "id"
      - "password"

scenarios:
  - name: "just login"
    flow:
      - get:
          url: "/search?query={{ id }}"
#      - post:
#          url: "/login-with-id-password"
#          json:
#            id: "{{ id }}"
#            password: "{{ password }}"